import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page } from "@playwright/test";

async function expectNoSeriousAccessibilityViolations(page: Page) {
  const results = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
    // Browser focus sentinels are injected by the test environment, and the
    // nested labelled SVG groups are generated by Observable Plot. The outer
    // charts and all project-owned controls remain in scope.
    .exclude("[data-tabster-dummy]")
    .exclude("g[aria-label]")
    .analyze();
  const serious = results.violations.filter(({ impact }) =>
    impact === "serious" || impact === "critical"
  );
  expect(serious).toEqual([]);
}

test("homepage assistant tasks and theme toggle remain usable", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator(".hero-subtitle")).toContainText(
    "Multimodal Data Integration Improves Disease Risk Prediction",
  );

  await page.getByRole("button", { name: "Open the Guided Research Assistant" }).click();
  await expect(page.getByRole("button", { name: /Understand the Research/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /Explore Visualizations/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /Build a Demo Profile/ })).toBeVisible();

  await expectNoSeriousAccessibilityViolations(page);
  await page.getByRole("button", { name: "Close the Guided Research Assistant" }).click();
  await page.getByRole("link", { name: "Toggle dark mode" }).click();
  await expect(page.locator("body")).toHaveClass(/quarto-dark/);
});

test("performance page loads local WebGL bundle and metric chart", async ({ page }) => {
  await page.goto("/viz/overall-performance.html");
  await expect(page.getByRole("heading", { name: /Overall Model Performance/ })).toBeVisible();
  await expect(page.getByPlaceholder("e.g. E11, diabetes, circulatory...")).toBeVisible();
  await expect(page.getByText(/10 models × 7 diseases/)).toBeVisible();
  await expect(page.getByText(/OJS (Runtime )?Error/)).toHaveCount(0);
  await expectNoSeriousAccessibilityViolations(page);
});

test("use-case page loads the Arrow patient embedding asset", async ({ page }) => {
  await page.goto("/viz/use-case.html");
  await expect(page.getByRole("heading", { name: /Use Case Study/ })).toBeVisible();
  await expect(page.getByText("114,285 patients").first()).toBeVisible();
  await expect(page.getByText(/OJS (Runtime )?Error/)).toHaveCount(0);
});
